---
--- 在list中更新某元素并同时删除多个元素
--- Generated by Luanalysis
--- Created by Tian.
--- DateTime: 2023/4/5 18:18
---

-- 参数列表
local listKey = KEYS[1];
-- 是否执行了清空操作,true为执行,false为未执行
local isEmpty = ARGV[1];
local t = ARGV[2];
-- 操作类型, update为更新, delete为删除
local op = ARGV[3];
-- 更新操作需要删除的键名pattern,符合该pattern的key都会被删除,格式:*pattern*
local delKeysPattern = ARGV[4];
local expireTime = ARGV[5];
-- 1.判断是否执行了清空操作,传入参数yes代表执行了清空操作,no代表没有执行
if(isEmpty=="no") then
-- 2.没有执行清空操作,代表redis中有该key
-- 2.1 则需要将list中t先删除
redis.call("lrem",listKey,"1",t);
    -- 判断操作类型
    if(op=="update") then
        -- 2.2 是更新,则再将t放到顶端
        redis.call("lpush",listKey,t);
    end
    -- 否则删除的话不需要重新将t放到顶端,更新和删除均需要重新设置过期时间
redis.call("expire",listKey,expireTime);
end
-- 3.删除所有需要删除的Key
local delKeys = redis.call("keys",delKeysPattern)
for i, v in ipairs(delKeys) do
    redis.call("del",v);
end
return true;